---
title: "Final"
format: html
author: Rylee sheils 
---

GitHub repository: [ENVS-193DS_winter-2026_final](https://github.com/ryleesheils/ENVS-193DS_winter-2026_final)

# Set Up 
```{r}
#| label: Set Up 
#| message: false
#| warning: false
library(tidyverse)
library(janitor)
library(forcats)
```

# Problem 1. Research writing

## a. Transparent Statisitcal Methods 
In part 1, they used a simple linear regression because they tested whether precipitation predicts flooded wetland area. In part 2, they used a Kruskal–Wallis rank-sum test because they tested whether median flooded wetland area differs across five water year classification groups.

## b. Figure Needed
A good figure for part 2 would be a box plot with water year classification on the x-axis and flooded wetland area on the y-axis. I think this would be the best choice because it makes it easy to compare the median flooded wetland area across all five groups and also shows how spread out the data are in each one. I would also add the individual data points so it is easier to see the variation and overlap between groups.

## c. Suggestions for Rewriting 
Precipitation did not significantly predict flooded wetland area in the San Joaquin River Delta. This result was based on a simple linear regression (test statistic = not provided, distribution = not provided, degrees of freedom = not provided, p = 0.11, α = significance level not provided).

Median flooded wetland area also did not differ significantly across water year classifications. This result was based on a Kruskal-Wallis rank-sum test comparing wet, above normal, below normal, dry, and critical drought years (test statistic = not provided, distribution = chi-squared, degrees of freedom = 4, p = 0.12, α = significance level not provided).

## d. Interpretation
One additional variable that could influence flooded wetland area is median daily Delta outflow during the spring management period. This would be a continuous variable, and it could affect flooded wetland area because the paper found flooded wetland area was weakly correlated with Delta outflow during a key time for wetland water management.

# Problem 2. Data Visualization 

## a. Cleaning and Summarizing 
